### ISSUE TITLE
libyaml support not being loaded when I install Ansible + pyyaml

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-centos8-ansible#10]
I have recently updated the Dockerfile to install `libyaml-devel`, but it seems like Ansible might still be using Python-based yaml parsing, judging by lackluster performance (see https://github.com/ansible/ansible/issues/72030), as well as the fact that `python3 -c 'import _yaml'` gives:

```
root@93e95ea9dc5a:/# python3 -c 'import _yaml'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named '_yaml'
```

See commit: https://github.com/geerlingguy/docker-centos8-ansible/commit/17a0c403fd7c7c632a6799d2bc20a5da4ca5a305

**Comment by dmlb2000** [comment]
What about installing the python3-pyyaml package?

**Comment by geerlingguy** [comment]
@dmlb2000 - Thanks, it looks like that makes it work! Not sure why Ansible's dependency on pyyaml doesn't result in the right version of pyyaml being installed.
