### ISSUE TITLE
Ansible Necessary?

### ISSUE THREAD

**Issue by ProfessorManhattan** [geerlingguy/docker-centos8-ansible#14]
Hey, I am using this image for running molecule tests. My question is why do we need to install Ansible? Shouldn't just SSH and Python be enough?

**Comment by geerlingguy** [comment]
I have Ansible on these images so they can be used to run Ansible playbooks within them if needed (since that is a use case I often have when doing testing—prevents me from having to also install Ansible on the host system, e.g. a CI runner).
