### ISSUE TITLE
Error using dnf.  Getting "Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist"

### ISSUE THREAD

**Issue by hectoralicea** [geerlingguy/docker-centos8-ansible#18]
using in a jenkins k8s docker slave

the following command in a jenkins pipeline stage
`            dnf clean all && rm -r /var/cache/dnf  && dnf install git --assumeyes --quiet
`

returns the following error
```
12:29:58  + dnf clean all
12:29:58  0 files removed
12:29:58  + rm -r /var/cache/dnf
12:29:58  + dnf install git --assumeyes --quiet

12:29:59  Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

According to https://hub.docker.com/r/geerlingguy/docker-centos8-ansible/ the image was updated 2 days ago

I will try an older image and see if that fixes the problem.

Stay tuned.

**Comment by carlosmmatos** [comment]
@hectoralicea https://forums.centos.org/viewtopic.php?f=54&t=78708

Might be time to migrate to rockylinux8, or perhaps we need to update the yum repos as noted in: https://www.centos.org/centos-linux-eol/

**Comment by geerlingguy** [comment]
@carlosmmatos if your PR passes I'll go ahead and merge. But yes, I no longer use this image and am considering archiving it as unsupported. I've moved on to `rockylinux8` for most of my testing.

**Comment by carlosmmatos** [comment]
@geerlingguy agreed with archiving this.. I've opened an issue #20 to suggest an alternative, as CentOS Stream is the new thing RH is pushing.
